### PR TITLE
DEV-3961 add locale to page editor

### PR DESCRIPTION
**Pull request by nrh-cklimas**
Please fill out each section even if it's just with "N/A"

#### Plan? (if this draft/incomplete indicate what you intend to do and how)

n/a

#### What's this PR do?

- Add Language section to the Setup tab of the page editor. This changes the locale setting of the page and is behind a feature flag.
- Renames `PageSetup` to `PageSettings` (since that's what the tab is named now) and migrates it to TypeScript.
- Removes dead code for `BenefitsWidget`, since it is not used anywhere.

#### Why are we doing this? How does it help us?

Allows users to set locale on a page.

#### Are there detailed, specific, step-by-step testing instructions in the associated ticket?

Yes.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?

We need to document the new dropdown menu, and screenshots may need to change as the panel layout has changed.

#### Have automated unit tests been added? If not, why?

Yes.

#### How should this change be communicated to end users?

Updated docs.

#### Are there any smells or added technical debt to note?

No.

#### Has this been documented? If so, where?

Don't know if we are starting to documentation Spanish language support yet.

#### What are the relevant tickets? Add a link to any relevant ones.

- https://news-revenue-hub.atlassian.net/browse/DEV-3961
- https://news-revenue-hub.atlassian.net/browse/ITS-2130

#### Do any changes need to be made before deployment to production (adding environment variables, for example)? If so, open a ticket and link it to the ticket for this PR and list it here:

Yes. https://news-revenue-hub.atlassian.net/browse/ITS-2130

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:

No.

### CODE REVIEW

**Review by GuiMend — APPROVED** [review]

**Comment by nrh-cklimas** [comment]
@GuiMend added logic to prevent the repeated modals you saw in 96c2adfee47c0beb6c624d165b3a975e9e333677

**Review by GuiMend — COMMENTED** [review]
Another comment @nrh-cklimas:

If I:
1. change language, 
2. click "Update", 
3. accept language modal changes, 
4. click "undo", (language is back to previously set)
5. change language again
6. click "update"
7. modal doesn't show. (I think if the user undo's the changes, the language warning modal should reset and reappear if they change languages again). What do you think?

image

If it's desired to keep it this way, I'm ok with approving this PR 👍

**Comment by nrh-cklimas** [comment]
@GuiMend addressed the undo button in d862f9c11b26218b4f03e54dafb2169a1543b161

**Review by GuiMend — APPROVED** [review]
👍

**Pull request merged**
