### PR TITLE
DEV-1760 MagicLink Email / Auth Logging

### PR DESCRIPTION
**Pull request by njharman**
#### What's this PR do?
Add bunch of temporary and rough logging around magic link email /
contributor page.

#### Why are we doing this? How does it help us?
To Debug auth issues DEV-1372

#### How should this be manually tested?
see DEV-1372

#### Have automated unit tests been added?
no, and I think adding logging lines coverage below 95%. This code is mess. I've already refactored for DEV-1372, Ben has also refactored a bit I think in one of his tickets.  
 
#### How should this change be communicated to end users?
N/A

#### Are there any smells or added technical debt to note?
Maybe found logic error in auth. See code comments.

All branches are not test covered. The structure of apps/api/authentication.py is a mess. Some times raising sometimes returning None, sometimes None, None among other chaos.

#### Has this been documented? If so, where?
ntmk

#### What are the relevant tickets?
[DEV-1760]  [DEV-1372]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
the logging has to be set to at least INFO 

#### Are there next steps? If so, what? Have tickets been opened for them?
Debugging!

[DEV-1760]: https://news-revenue-hub.atlassian.net/browse/DEV-1760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1372]: https://news-revenue-hub.atlassian.net/browse/DEV-1372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by x110dc — CHANGES_REQUESTED** [review]
Looks good, but I thought logging calls should generally use `%` formatting instead of f-string style?

**Comment by x110dc** [comment]
Also, there's a merge conflict in `apps/api/views.py`.

**Comment by njharman** [comment]
> Looks good, but I thought logging calls should generally use `%` formatting instead of f-string style?

Correct. Muscle memory,  I wrote this very fast to get it in before I was gone for several days. Aren't (most) these temporary just for debugging?

Fixing.

**Comment by njharman** [comment]
@x110dc did you notice my PR line 
> Maybe found logic error in auth. See code comments.

I'm 60-70% feeling that was bug causing issues?

**Comment by njharman** [comment]
The lack to testing will be resolved in [DEV-1372] when fixing underlying bug.

**Pull request closed without merging**
