### PR TITLE
Dev 3042 add sentry user celery

### PR DESCRIPTION
**Pull request by harsha09**
#### What's this PR do?
Adds email to sentry logs for celery app.

#### Why are we doing this? How does it help us?
Effectively identify the user for resolution.

#### How should this be manually tested? Please include detailed step-by-step instructions.
Two places we can test this,
1. Sending E-Mail
2. Viewing contributions for a contributor using magic link (Sends out lot of warnings if the logging is enabled for WARN level)
Need to manually raise the exception in the code.

#### Did this PR make changes to the user interface that may require changes to the user-facing docs?
NA

#### Have automated unit tests been added? If not, why?
This a configuration change, there were no tests for sentry prior also.

#### How should this change be communicated to end users?
NA

#### Are there any smells or added technical debt to note?
NA

#### Has this been documented? If so, where?
NA

#### What are the relevant tickets? Add a link to any relevant ones.
[DEV-3042]

#### Do any changes need to be made before deployment to production (adding environment variables, for example)?
NA

#### Are there next steps? If so, what? Have tickets been opened for them? List next-step tickets here:
NA

[DEV-3042]: https://news-revenue-hub.atlassian.net/browse/DEV-3042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by njharman — CHANGES_REQUESTED** [review]
Why is send_thank_you_email not also updated to sentry email.

**Comment by benjaminEwhite** [comment]
Closing, tearing down, then reopening as part of work for [DEV-3243 | fix hookdeck webhooks](https://news-revenue-hub.atlassian.net/browse/DEV-3243), to trigger fresh review app.

**Review by x110dc — CHANGES_REQUESTED** [review]
I'm a little confused about the implementation here. The documentation here: https://docs.sentry.io/platforms/python/guides/celery/enriching-events/identify-user/ just mentions using using 

`set_user({"email": "jane.doe@example.com"})`

And nothing about using `configure_scope`. Can you explain?

**Comment by harsha09** [comment]
> 

@x110dc: Here is the documentation, using `configure_scope` for setting the current authenticated user to the current scope. https://docs.sentry.io/platforms/python/guides/logging/enriching-events/scopes/
`configure_sope` function returns a context manager which yields the current scope when a client associated with it otherwise creates a new scope and yeilds.

**Review by x110dc — APPROVED** [review]

**Review by njharman — APPROVED** [review]

**Pull request merged**
